### ISSUE TITLE
Project Question

### ISSUE THREAD

**Issue by thompcd** [MarcusCalidus/s7-plc-exporter#7]
Hi!

I'm trying to understand what role this project plays. Is this a remote server that will use snap7 to scrap the data from the PLC and aggregate it, so the PLC is unaware of the logging service?

I've got an S7 1200 for that I don't have access to source or the licensing to TIA portal at the moment but was hoping to do something like this if no settings need to be adjusted. Have you deployed your project in a docker container by any chance?

Looks very cool!

Thanks

**Comment by MarcusCalidus** [comment]
the exporter will connect to the S7 PLC via Ethernet. It uses the Snap7 Library (http://snap7.sourceforge.net) to access the DBs, Markers, Inputs and Outputs. The PLC does not have to be changed for that. 

The only problem that you might encounter is, that you definitely need to know the addresses of the data in the memory of the PLC. Since you don't have access to the TIA portal that would be your biggest hurdle. I don't think it is possible to guess or reverse engineer the data structure. Any chance to get hold of the original PLC developers?

At the moment I don't have a docker container prepared. If necessary I can look into that. But I won't come around that this week.
